### PR TITLE
Add new apt_info.py script

### LINKED ISSUE #85: apt.sh includes stats about packages that aren't even installed
I have an alert setup to notify me if any of my machines are failing to install security updates. Today I'm getting alerts for a machine that actually has no security updates available:

```
$ apt list --upgradable
Listing... Done
apport/focal-updates 2.20.11-0ubuntu27.14 all [upgradable from: 2.20.11-0ubuntu27.13]
cloud-init/focal-updates 20.4.1-0ubuntu1~20.04.1 all [upgradable from: 20.3-2-g371b392c-0ubuntu1~20.04.1]
libasound2-data/focal-updates 1.2.2-2.1ubuntu2.3 all [upgradable from: 1.2.2-2.1ubuntu2.2]
libasound2/focal-updates 1.2.2-2.1ubuntu2.3 amd64 [upgradable from: 1.2.2-2.1ubuntu2.2]
libdrm-common/focal-updates 2.4.102-1ubuntu1~20.04.1 all [upgradable from: 2.4.101-2]
libdrm2/focal-updates 2.4.102-1ubuntu1~20.04.1 amd64 [upgradable from: 2.4.101-2]
libnetplan0/focal-updates 0.101-0ubuntu3~20.04.2 amd64 [upgradable from: 0.100-0ubuntu4~20.04.3]
libnss-systemd/focal-updates 245.4-4ubuntu3.4 amd64 [upgradable from: 245.4-4ubuntu3.3]
libpam-systemd/focal-updates 245.4-4ubuntu3.4 amd64 [upgradable from: 245.4-4ubuntu3.3]
libsystemd0/focal-updates 245.4-4ubuntu3.4 amd64 [upgradable from: 245.4-4ubuntu3.3]
libudev1/focal-updates 245.4-4ubuntu3.4 amd64 [upgradable from: 245.4-4ubuntu3.3]
lsof/focal-updates 4.93.2+dfsg-1ubuntu0.20.04.1 amd64 [upgradable from: 4.93.2+dfsg-1]
netplan.io/focal-updates 0.101-0ubuntu3~20.04.2 amd64 [upgradable from: 0.100-0ubuntu4~20.04.3]
python3-apport/focal-updates 2.20.11-0ubuntu27.14 all [upgradable from: 2.20.11-0ubuntu27.13]
python3-problem-report/focal-updates 2.20.11-0ubuntu27.14 all [upgradable from: 2.20.11-0ubuntu27.13]
sosreport/focal-updates 4.0-1~ubuntu0.20.04.3 amd64 [upgradable from: 4.0-1~ubuntu0.20.04.2]
systemd-sysv/focal-updates 245.4-4ubuntu3.4 amd64 [upgradable from: 245.4-4ubuntu3.3]
systemd-timesyncd/focal-updates 245.4-4ubuntu3.4 amd64 [upgradable from: 245.4-4ubuntu3.3]
systemd/focal-updates 245.4-4ubuntu3.4 amd64 [upgradable from: 245.4-4ubuntu3.3]
udev/focal-updates 245.4-4ubuntu3.4 amd64 [upgradable from: 245.4-4ubuntu3.3]
update-notifier-common/focal-updates 3.192.30.4 all [upgradable from: 3.192.30]
```

I found this very confusing until I looked closer at `apt.sh` and realized it was using `apt-get --just-print dist-upgrade` to extract its information. I checked the output of that command, and there is indeed something coming from -security:

```
$ apt-get --just-print dist-upgrade
NOTE: This is only a simulation!
      apt-get needs root privileges for real execution.
      Keep also in mind that locking is deactivated,
      so don't depend on the relevance to the real current situation!
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  libfreetype6
Use 'apt autoremove' to remove it.
The following NEW packages will be installed:
  alsa-utils libatopology2 libfftw3-single3 libgomp1 libpciaccess0 libsamplerate0 python3-xkit ubuntu-drivers-common
The following packages will be upgraded:
  apport cloud-init libasound2 libasound2-data libdrm-common libdrm2 libnetplan0 libnss-systemd libpam-systemd libsystemd0 libudev1 lsof
  netplan.io python3-apport python3-problem-report sosreport systemd systemd-sysv systemd-timesyncd udev update-notifier-common
21 upgraded, 8 newly installed, 0 to remove and 0 not upgraded.
<snip>
Inst libgomp1 (10.2.0-5ubuntu1~20.04 Ubuntu:20.04/focal-updates, Ubuntu:20.04/focal-security [amd64])
<snip>
Conf libgomp1 (10.2.0-5ubuntu1~20.04 Ubuntu:20.04/focal-updates, Ubuntu:20.04/focal-security [amd64])
<snip>
```

However, take a closer look at that output:

> The following NEW packages will be installed:
>   alsa-utils libatopology2 libfftw3-single3 **libgomp1** libpciaccess0 libsamplerate0 python3-xkit ubuntu-drivers-common

Which means this isn't actually a security update at all-- `libgomp1` isn't even installed. It's a new dependency added by something that _isn't_ a security update, and thus will not be installed (because my production instances only install security updates automatically).

This makes me think that `apt-get --just-print dist-upgrade` isn't the right tool for the job. Thoughts?

### LINKED ISSUE #90: apt.sh include kept-back packages
Hi. My use-case for this script was to check if we have updates for our mongodb server machines. However, to reduce the risk of accidentally running `apt upgrade` and upgrading the mongodb binaries, we have kept them back. These are the exact packages I wanted their results in my metrics, but because of them not being upgraded by `apt upgrade`, they are not shown in the captured result by this script.
I tried adding `--with-new-pkgs` to the executed `apt --just-print upgrade` command, but it complains:
```
E: Command line option --with-new-pkgs is not understood in combination with the other options
```
Is there any solution to what I want here?

### PR DESCRIPTION
**Pull request by kyrofa**
Currently, apt information is extracted via a shell script by way of `apt-get --just-print dist-upgrade`, and it has a number of issues. For example, it includes held packages in the metrics, and includes information about packages that aren't even installed. This PR fixes #85 and fixes #90 by replacing `apt.sh` with a new Python-based script that uses the APT API to extract everything we need, while fixing known issues and remaining mostly compatible with the old metric format.

### CODE REVIEW

**Comment by kyrofa** [comment]
Hey @dswarbrick, thoughts on this? I believe it fixes a number of issues.

**Comment by radupopa2010** [comment]
`apt.sh`  still has issues today: It reports that packages should be upgraded when the output of `apt-get --just-print upgrade` says that packages were downgraded  
```
root@REMOVED[15:17] /etc/apt # date
Mon 25 Jul 2022 03:17:51 PM UTC


root@REMOVED[15:01] /etc/apt # apt-get --just-print upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be DOWNGRADED:
  containerd.io docker-ce docker-ce-cli docker-ce-rootless-extras
0 upgraded, 0 newly installed, 4 downgraded, 0 to remove and 0 not upgraded.
Inst containerd.io [1.6.6-1] (1.6.4-1 Docker CE:bullseye [amd64])
Inst docker-ce-cli [5:20.10.17~3-0~debian-buster] (5:20.10.16~3-0~debian-bullseye Docker CE:bullseye [amd64])
Inst docker-ce [5:20.10.17~3-0~debian-buster] (5:20.10.16~3-0~debian-bullseye Docker CE:bullseye [amd64])
Inst docker-ce-rootless-extras [5:20.10.17~3-0~debian-buster] (5:20.10.16~3-0~debian-bullseye Docker CE:bullseye [amd64])
Conf containerd.io (1.6.4-1 Docker CE:bullseye [amd64])
Conf docker-ce-cli (5:20.10.16~3-0~debian-bullseye Docker CE:bullseye [amd64])
Conf docker-ce (5:20.10.16~3-0~debian-bullseye Docker CE:bullseye [amd64])
Conf docker-ce-rootless-extras (5:20.10.16~3-0~debian-bullseye Docker CE:bullseye [amd64])

root@REMOVED[15:17] /etc/apt # /usr/share/prometheus-node-exporter-collectors/apt.sh
# HELP apt_upgrades_pending Apt package pending updates by origin.
# TYPE apt_upgrades_pending gauge
apt_upgrades_pending{origin="DockerCE:bullseye",arch="amd64"} 4
# HELP apt_autoremove_pending Apt package pending autoremove.
# TYPE apt_autoremove_pending gauge
apt_autoremove_pending 0
# HELP node_reboot_required Node reboot is required for software updates.
# TYPE node_reboot_required gauge
node_reboot_required 0

```

**Comment by kyrofa** [comment]
Yeah, it's pretty terrible. I haven't gotten any traction here, though :cry: .

**Comment by radupopa2010** [comment]
Hey @mrueg @dswarbrick  need your help merging this please

**Comment by SuperQ** [comment]
Thanks, this looks good.

Can you mention at the top of the script what packages may need to be installed for this to work, like I assume `apt-get install python3-apt` is necessary on some of the more slim Debian installs.

**Comment by kyrofa** [comment]
Of course-- done.

**Review by SuperQ — APPROVED** [review]
Thanks!

**Comment by SuperQ** [comment]
If you're interested in writing more Python code here. One of the things I have been thinking about doing is replacing all of the `print()` statements with a client_python registry and calling a single registry print to stdout at the end of main().

**Comment by radupopa2010** [comment]
Thank you for the very fast reply @SuperQ

**Pull request merged**
