### PR TITLE
add hddtemp collector

### PR DESCRIPTION
**Pull request by andresbott**
this textfile collector uses hddtempd to get the disks and disk temperatures, and expose as prometheus metric with one label per disk.

### CODE REVIEW

**Comment by dswarbrick** [comment]
Isn't this somewhat redundant, given that there are already two SMART collectors in this repo, which are capable of fetching HDD temperatures (and much more)?

**Comment by AndresBott** [comment]
maybe ... i haven't seen the smart collector before.
I will try it out to see if it is a better fit.

**Comment by AndresBott** [comment]
After a quick check on my server smartmon.sh seems to completely cover the temperature feature.
The only drawbacks for smartmon.sh is that the the script needs to run as root, as where as hddtempd can be read as a normal user.

I'll let you decide if you want to merge or not, I guess since it is already covered by smart we can close this.

**Comment by dswarbrick** [comment]
Whilst this script might not require root privileges, the hddtempd daemon that it talks to _does_ need to run as root (and I expect that at some level, is sending the same SMART commands via SCSI generic ioctl that `smartctl` does). A sudo wrapper script would also arguably not require root access.

Given the number of unfixed typos in this PR, and the fact that the smartmon collector already fulfills this niche... closing.

**Pull request closed without merging**
